# Generated by Django 3.0.4 on 2020-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20200312_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Studenten_ID'),
        ),
    ]
